spring:
  application:
    name: echo-app
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Iv23li8ZlzrZJivZZ9PT
            client-secret: 36bf9672495a8b81746809879e63188608b2a330
  data:
    cassandra:
      keyspace-name: main
      username: qaxPziAqUnRaiuCZdUXiPUaO
      password: CAS_GngBbkM4NZk46J2QMzQL…PGkCPPICm0PS4xw.UNg8RaM
      schema-action: recreate-drop-unused
      request:
        timeout: 10s
      connection:
        connect-timeout: 10s
        init-query-timeout: 10s

  astra.db:
    id: qaxPziAqUnRaiuCZdUXiPUaO
    region: eu-west-1
    keyspace: main
    application.token: AstraCS:qaxPziAqUnRaiuCZdUXiPUaO:687a015d6e6fda5d65fc286f8cb3b6e9e48ffd1c5b16dfbb331e2ca6102f242b

  datastax.astra:
    secure-connect-bundle: secure-connect-echo-app.zip


